# from base_prometheus.yml
global:
  scrape_interval: 15s

# Load a directory of JSON configs
scrape_configs:
  - job_name: 'stub'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json
