global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  receiver: 'unmatched-default-root-route'

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

receivers:
- name: 'unmatched-default-root-route'
  email_configs:
  - to: 'devopsteam@example.org'
    send_resolved: true
